apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
  labels:
    app: nginx
    type: load-balancer
spec:
  volumes:
  - name: volume-hostpath 		
    hostPath: 
      path: /tmp/hostpath/       
      type: DirectoryOrCreate
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
     - containerPort: 80
    volumeMounts:
     - mountPath: /home
       name: volume-hostpath
