apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  affinity:
    nodeAffinity: 
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: spec
              operator: In
              values:
              - test
        - weight: 5
          preference:
            matchExpressions:
            - key: spec
              operator: In
              values:
              - medium
