apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: alpine
    os: linux
spec:
  containers:
  - name: alpine
    image: alpine
    args:
    - /bin/sh
    - -c
    - touch /home/temp/probecheck; sleep 20; rm /home/temp/probecheck; sleep 1000
    livenessProbe:
      exec:
        command:
        - cat
        - /home/temp/probecheck
      initialDelaySeconds: 2
      periodSeconds: 5
      failureThreshold: 5
