apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: svc-crb
subjects:
  - kind: ServiceAccount
    name: svc
    namespace: default
roleRef:
  kind: ClusterRole
  name: svc-cr
  apiGroup: rbac.authorization.k8s.io
